apiVersion: apps/v1
kind: Deployment

metadata:
  name: kuborder-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kuborder-backend

  template:
    metadata:
      labels:
        app: kuborder-backend

    spec:
      containers:
      - name: backend
        image: ghcr.io/lakshya-8000cr/kuborder-backend:latest
        imagePullPolicy: Always

        envFrom:
        - configMapRef:
            name: app-config
        
        env:
         - name: ORDDERS_FILE
           value: /app/persistent/orders.json

        ports:
        - containerPort: 3000

        volumeMounts:
        - name: kuborder-data
          mountPath: /app/persistent

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

      volumes:
      - name: kuborder-data
        persistentVolumeClaim:
          claimName: kuborder-data-pvc