apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.backend.name }}

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.backend.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}

    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

        envFrom:
        - configMapRef:
            name: app-config

        ports:
        - containerPort: {{ .Values.backend.port }}

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"