backend:
  name: kuborder-backend
  replicas: 0
  image:
    repository: ghcr.io/lakshya-8000cr/kuborder-backend
    tag: latest
    pullPolicy: Always
  port: 3000

frontend:
  name: kuborder-frontend
  replicas: 0
  image:
    repository: 1
    tag: latest
    pullPolicy: Always
  port: 80

config:
  APP_NAME: Kuborder
  ENVIRONMENT: development
  APP_VERSION: v1